apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'istio-base'
spec:
  project: default
  source:
    chart: base
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.14.1
    helm:
      releaseName: istio-base
  destination:
    name: 'in-cluster'
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
